variable_name:
  min_length:
    warning: 0
    error: 0
disabled_rules:
  - large_tuple
  - type_name
  - function_parameter_count
  - nesting
  - file_length
  - force_cast
  - function_body_length
  - todo
  - type_body_length
  - line_length
  - cyclomatic_complexity
  - identifier_name
  - multiple_closures_with_trailing_closure
excluded:
  - Pods
  - AwesomeSwiftUI/Generated
  - AwesomeSwiftUI/Apollo
  - "AwesomeSwiftUITests"